name: Deploy Discord AnagariBot

on:
  # schedule:
    #Запускать каждые 10 минут
    # - cron: '*/10 * * * *'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Load Environment Variables
        run: |
          echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> $GITHUB_ENV
          echo "GIT_PAT_TOKEN=${{ secrets.GIT_PAT_TOKEN }}" >> $GITHUB_ENV
          echo "API_KEY_ROBLOX=${{ secrets.API_KEY_ROBLOX }}" >> $GITHUB_ENV
          echo "PRIVATE_KEY_ID_GOOGLE=${{ secrets.PRIVATE_KEY_ID_GOOGLE }}" >> $GITHUB_ENV
          echo "PRIVATE_KEY_GOOGLE=${{ secrets.PRIVATE_KEY_GOOGLE }}" >> $GITHUB_ENV
          echo "SPREADSHEET_ID_GOOGLE=${{ secrets.SPREADSHEET_ID_GOOGLE }}" >> $GITHUB_ENV

      - name: Run bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        run: |
          echo "Starting the bot..."
          python main.py
